### ISSUE TITLE
Cannot create Client App on GAuth 

### ISSUE THREAD

**Issue by rowiebiz82** [genesys/multicloud-services#109]
### What happened?

I am always getting Bad Credential whenever running curl to create client API. I am seeing errors shown on the logs provided. Should the value of password on the deployment-secrets be bcrypt encoded instead of base64?

### Cluster

GKE

### What service are you having issues with?

gws

### Relevant log output

```shell
│ {"@timestamp":"2022-08-11T16:55:36.178Z","@version":"1","msg":"Using pattern-based contact-center resolution for user","logger_name":"com.genesys.gws.v3.auth.impl.ContactCenterLookupSer │
│ {"@timestamp":"2022-08-11T16:55:36.285Z","@version":"1","msg":"Encoded password does not look like BCrypt","logger_name":"org.springframework.security.crypto.bcrypt.BCryptPasswordEncode │
│ {"@timestamp":"2022-08-11T16:55:36.287Z","@version":"1","msg":"Authentication error received: [[org.springframework.security.authentication.BadCredentialsException: Bad credentials]]","
```

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by DFHicks** [comment]
Hello @rowiebiz82 

What was set for the gauth account details? 

You are correct, the `services.secret.admin_password` and `services.secret.client_secret` would be in bcrypt.
 
https://all.docs.genesys.com/AUTH/Current/AuthPEGuide/Configure

**Comment by DFHicks** [comment]
@rowiebiz82 Documentation has been updated to reflect example values. Please let us know if the issue persists.

**Comment by rowiebiz82** [comment]
Hi Dan,

Yeah the issue persisted even after switching to bcrypted password. Somehow the only workaround is manually edit the gauth password on gauth-client secret. The one deployed via the GitHub Workflow process is not working.

The deployment-secrets has below password:

$2a$10$nhYQfpiPA2X76P33cYnqSu/umxMX2semH48tGSMijLyW2XjOi1p4i  => equal to secret

the secret admin_password has below:

$2a$10/umxMX2semH48tGSMijLyW2XjOi1p4i

Regards,

Rowell
