### ISSUE TITLE
Error encountered when Running workflow for Infra Components

### ISSUE THREAD

**Issue by CRagoGenesys** [genesys/multicloud-services#11]
Get the following error in Customer scripts when trying to install components for example postgres, redis and even using install to install all components as stated in readme.

/home/runner/work/_temp/1fb1793b-5b58-483b-a863-609c5df9c25f.sh: line 29: postgres: command not found
Error: Process completed with exit code 127.

**To Reproduce**
1. Go to Actions and Run workflow
2. Use the following parameters:

![image](https://user-images.githubusercontent.com/101691286/170056869-5047cf22-8f9d-40bd-8244-2d90034d50e4.png)

3.) Replacing the Commands with "install redis", "install consul" leads to the same error.
4.)  

**Expected behavior**
Deploy the components in GKE Cluster.

Will attach the workflow logs.

[Using install consul in command.zip](https://github.com/genesys/multicloud-services/files/8763644/Using.install.consul.in.command.zip)
[Using install postgres in command while changing bitnami as helm repo name.zip](https://github.com/genesys/multicloud-services/files/8763645/Using.install.postgres.in.command.while.changing.bitnami.as.helm.repo.name.zip)
[Using install postgres in command.zip](https://github.com/genesys/multicloud-services/files/8763646/Using.install.postgres.in.command.zip)
[Using only install in command.zip](https://github.com/genesys/multicloud-services/files/8763647/Using.only.install.in.command.zip)
[Using only validate in command.zip](https://github.com/genesys/multicloud-services/files/8763648/Using.only.validate.in.command.zip)

**Comment by DFHicks** [comment]
Hello CJ,

Please update the version in chart.ver to the latest postgres build available from bitnami.

Our db segmentation update includes this as well. (estimated May 31st)

```
helm search repo postgresql --devel

NAME                    CHART VERSION   APP VERSION     DESCRIPTION
bitnami/postgresql      11.2.6          14.3.0          PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql-ha   9.0.12          14.3.0          This PostgreSQL cluster solution includes the P.../
```

**Comment by CRagoGenesys** [comment]
Hi Dan,

Thanks for the feedback. I updated chart version to 11.2.6 in my repo

https://github.com/CRagoGenesys/RagzCloud/blob/main/infra/01_chart_postgresql/chart.ver

However I still got the same problem.

/home/runner/work/_temp/1c7292bf-8fa8-4e2d-aa49-563001d73e31.sh: line 29: postgres: command not found
Error: Process completed with exit code 127.

Is there a way to get these temp files from github hosted runner or it would be available if we run self-hosted runner?

https://github.com/CRagoGenesys/RagzCloud/blob/main/infra/01_chart_postgresql/chart.ver

![image](https://user-images.githubusercontent.com/101691286/170170327-5e12e5cd-0ae9-4ab0-b3ef-542c95d864bd.png)

Adding the workflow log

[install postgres.zip](https://github.com/genesys/multicloud-services/files/8767567/install.postgres.zip)

[rawlogs.txt](https://github.com/genesys/multicloud-services/files/8767571/rawlogs.txt)

Regards,
Cesar
