### ISSUE TITLE
[BUG]: Tenat installation Error.

### ISSUE THREAD

**Issue by xuheng44** [genesys/multicloud-services#113]
### What happened?

report kubectl errors for init_db when run pre-release-script.sh.

Found the wrong setting for kubectl.

current wrong script:
kubectl run busybox -i -rm --image=alpine --restart=Never -- sh -c "$(<init_db.sh_)"

Right script:
kubectl run busybox -i --rm --image=alpine --restart=Never -- sh -c "$(<init_db.sh_)"

Another question:
What is "LOCATION" for override_values.yaml?
location: "${LOCATION}"

I only can find related setting in gauth service, default is USW1, whether i should use this settings?

thanks
sky

### Cluster

generic kubernetes

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by DFHicks** [comment]
Yes, location would align with what you've selected for GAUTH.
If you used USW1 for GAUTH, add to your deployment-secrets 
`  LOCATION: USW1 `
