### ISSUE TITLE
[BUG]: GWS Client ids set up

### ISSUE THREAD

**Issue by shubhamsinghania** [genesys/multicloud-services#122]
### What happened?

https://github.com/genesys/multicloud-services/blob/main/examples-gke/github-actions/gws/01_chart_gws-services/override_values.yaml

Above file refers client id as below:
  gwsAppWorkspace:
    clientId: gws_client_id
  gwsAppProvisioning:
    clientId: gws_client_id

But secret are referred differently:
  gws-app-provisioning-client-secret: gws_app_provisioning
  gws-app-workspace-client-secret: gws_app_workspace

Based on the deployment secret that is created for GWS, understanding is, for app workspace and app provisioning should have different client id and secret. Either documentation for deployment secret should get updated to use same secret value for app workspace and app provisioning or override file should get updated with correct client id names for these 2 services.

### Cluster

GKE

### What service are you having issues with?

gws

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by DFHicks** [comment]
@shubhamsinghania thank you for the suggestion. v0.6.0.0 has been updated with additional clarification.

**Comment by xuheng44** [comment]
@DFHicks 

I also confused about these two values.

may i ask what i should set for gws_app_provisioning and gws_app_provisioning in deployment_secrets.yaml?
whether i can leave default value "sample" or change to other values?

Thanks
Sky

**Comment by DFHicks** [comment]
@xuheng44 readme has been updated with default value and description.

**Comment by xuheng44** [comment]
@DFHicks 

Sorry, just want to confirm whether the two values should be bcrypt encode too?

Thanks
Sky

**Comment by LakeUtopianFir** [comment]
@xuheng44 

These secrets are the encrypted secrets generated and stored in GAUTH db by creating the clients themselves. 
You would receive this secret value in the body of the 200OK received when executing the POST to gauth/auth api. 

You can find this value by querying gauth db 

``select * from auth.oauth_client_details where client_id = '<client_name>';``

*note*: GWS is one of the limited services that will use this secret instead of the plain text value used in the creation of the client.

**Comment by xuheng44** [comment]
@LakeUtopianFir 
Thanks for your reply.
I had double checked script(pre-release-sh.sh) in gws directory, not found how to call gauth services to create them?
Whether it means it will be created during gws-services installation?
If those secrets will be created during gws-services installations, whether i should put the plain text in the deployment_secrets.yaml?

Thanks
Sky

thanks
Sky
