### ISSUE TITLE
[DOC]: GWS Location

### ISSUE THREAD

**Issue by shubhamsinghania** [genesys/multicloud-services#123]
### What did you find?

https://github.com/genesys/multicloud-services/tree/main/examples-gke/github-actions/gws

Read me should get updated where global_location (for deployment secret) should be LOCATION.

As pre-release-script.sh has this:
export global_location=$( get_secret LOCATION )

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by DFHicks** [comment]
@shubhamsinghania thank you for the info. v0.6.0.0 has been updated with additional clarification.
