### ISSUE TITLE
[DOC]: GWS and GAUTH location format causing issue

### ISSUE THREAD

**Issue by shubhamsinghania** [genesys/multicloud-services#124]
### What did you find?

For gauth and gws documentation, for deployment secret we had to change location format from USW1 to /USW1. It will be good if some research can be done around this to see how this is working with "USW1" in your GCP environment and update the documentation or steps accordingly.

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by DFHicks** [comment]
@shubhamsinghania thank you for the suggestion. v0.6.0.0 has been updated with additional clarification.
