### ISSUE TITLE
[FEATURE]: Voice ORS

### ISSUE THREAD

**Issue by shubhamsinghania** [genesys/multicloud-services#129]
### What is needed?

I noticed that, the chart version that is supplied by default for Voice ORS service is 100.0.1000017. When we deploy ORS with this chart version we get below error:

  Warning  FailedCreate  14m (x455 over 4d23h)  statefulset-controller  create Pod voice-ors-0 in StatefulSet voice-ors failed error: Pod "voice-ors-0" is invalid: spec.containers[0].volumeMounts[5].name: Not found: "config-options"

It seems there was a fix for this issue in later version of chart 100.0.1000018.

It will be good if we can update the default version of chart (and docker image version if needed) in this repo so that if customers are trying to use the repo as is for initial lab deployments they dont run into this issue.

### Possible solutions.

Update chart version for voice ORS

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by DFHicks** [comment]
@shubhamsinghania there is a monthly cadence to the versions provided in the examples. By all means update the releases to match what is currently available from Genesys.
