### ISSUE TITLE
[BUG]:  Can't create new API client.

### ISSUE THREAD

**Issue by xuheng44** [genesys/multicloud-services#142]
### What happened?

Try to create New API Client based on https://all.docs.genesys.com/AUTH/Current/AuthPEGuide/Provision.

always report Bad credentials.
[genesys@gauth-auth-675597946c-fq9vp application]$ curl --location --request POST 'http://gauth-auth/auth/v3/ops/clients' --header 'Content-Type: application/json' --user gadminUser:$2y$10$a5znBNI3dr5q38jreJAj/ew/bdtpWDZ3FooLIBYMwxmlTU6Qm3qKy --data-raw '{"data": {
>     "name": "external_api_client", 
>     "clientType": "CONFIDENTIAL",
>     "internalClient": true,
>     "refreshTokenExpirationTimeout": 43200,
>     "client_id": "external_api_client", 
>     "client_secret": "secret", 
>     "authorities": ["ROLE_INTERNAL_CLIENT"],
>     "scope": ["*"],
>     "authorizedGrantTypes": ["client_credentials", "authorization_code", "refresh_token", "password"],    "redirectURIs": ["https://gauth.multicloud.gclubchina.com","https://wwe.multicloud.gclubchina.com","https://gws.multicloud.gclubchina.com",:q:"https://prov.multicloud.gclubchina.com"], 
>     "accessTokenExpirationTimeout": 43200
>     }
> }'
{"error":"Unauthorized","error_description":"Bad credentials"}[genesys@gauth-auth-675597946c-fq9vp application]

My deployment-secrets.yaml is as follow:
apiVersion: v1
stringData:
  DB_NAME: gauth
  POSTGRES_ADDR: pbdb-gws-postgresql.infra.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: un1H7aJghC
  gauth_admin_password: $2y$10$a5znBNI3dr5q38jreJAj/ew/bdtpWDZ3FooLIBYMwxmlTU6Qm3qKy
  gauth_admin_username: gadminUser
  gauth_gws_client_id: gauth_client
  gauth_gws_client_secret: $2y$10$a5znBNI3dr5q38jreJAj/ew/bdtpWDZ3FooLIBYMwxmlTU6Qm3qKy
  gauth_jks_keyPassword: KeyPass
  gauth_jks_keyStorePassword: keyStorePass
  gauth_pg_password: gpgPASS
  gauth_pg_username: gpgUSER
  gauth_redis_password: PKaBMw4QpL
  LOCATION: USW1
kind: Secret
metadata:
  name: deployment-secrets
  namespace: gauth
type: Opaque
~             
so i think username should be gadminUser, password should be $2y$10$a5znBNI3dr5q38jreJAj/ew/bdtpWDZ3FooLIBYMwxmlTU6Qm3qKy, which is copied from README.

I also tried other combinations, such as ops/ops, gadminUser/ops, but all failed.

Any suggestions?

Thanks
Sky

### Cluster

generic kubernetes

### What service are you having issues with?

gauth

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by AndyVoutour** [comment]
@xuheng44 this is not an error with the pipeline (this repo is for the pipeline, so these 'issues' are issues with the public repo or pipelines in the repo), why was this issue opened? **It should be opened against Genesys Customer Care.**

Check in your gauth namespace secrets for the gauth-client secret. Check the value of admin_username, that's the username you use. The password you send is the plaintext value of your bcrypted secret, $2y$10$a5znBNI3dr5q38jreJAj/ew/bdtpWDZ3FooLIBYMwxmlTU6Qm3qKy .

I'm not sure what that decodes to, but our default $2a$10$7.jOOym2GhhVtpSPXOQmweVqY4gLKOXFbNDRul7UMeP40kQVVx/au decodes to 'ops', so ops:ops is the default.

This is a warning that future 'issues' opened that are not directly related to the pipeline or the public repo itself will be closed with a comment to open a Care case.

If you continue to have problems with this, please open a case against Genesys Customer Care.
