### ISSUE TITLE
[FEATURE]: Install webRTC without External LB.

### ISSUE THREAD

**Issue by xuheng44** [genesys/multicloud-services#151]
### What is needed?

During webRTC installation,  it need to get the external LB ip address for gateway installation, but hope can install it without external LB for LAB system.

[genesys@VM-4-14-centos gateway-blue]$ k get svc  -n webrtc
NAME                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
webrtc-coturn-service-blue    LoadBalancer   10.152.183.171   <pending>     80:31566/TCP      34m
webrtc-gateway-service-blue   ClusterIP      10.152.183.152   <none>        80/TCP,8080/TCP   34m

### Possible solutions.

Install webRTC without external LB.

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by AndyVoutour** [comment]
@xuheng44 can you confirm installing MetalLB (per our discussion) resolved this, and you were able to get an external IP (the microk8s node IP)?

**Comment by xuheng44** [comment]
@AndyVoutour Yes, I can get the external IP by enable MetaLB.

I close this case first.
