### ISSUE TITLE
[BUG] kafka-shared-secret-eastus2-dev errors in voice-agent installation.

### ISSUE THREAD

**Issue by xuheng44** [genesys/multicloud-services#24]
Hi Team,

When i use helm to install voice-agent and voice-agent is hold on "init:0/2" status.

And i describe that POD, and found below errors:

Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    3m18s                default-scheduler  Successfully assigned voice/voice-agent-689b966fcd-646h7 to vm-4-14-centos
  Warning  FailedMount  76s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[kafka-shared-secret-westus2-dev kafka-shared-secret-eastus2-dev], unattached volumes=[kafka-shared-secret-westus2-dev kafka-shared-secret-eastus2-dev consul-connect-inject-data kube-api-access-tgt8m consul-shared-secret redis-cache-secret redis-tenant-secret]: timed out waiting for the condition
  Warning  FailedMount  71s (x9 over 3m19s)  kubelet            MountVolume.SetUp failed for volume "kafka-shared-secret-westus2-dev" : secret "kafka-secrets-token-westus2-dev" not found
  Warning  FailedMount  71s (x9 over 3m19s)  kubelet            MountVolume.SetUp failed for volume "kafka-shared-secret-eastus2-dev" : secret "kafka-secrets-token-eastus2-dev" not found

I had double checked all the scripts and deployement-secret.yaml/override_values.yaml for voice-agents, i can't find any settings for kafka?  Mayi ask how to solve it?

Thanks
Sky

**Comment by DFHicks** [comment]
@xuheng44 could you please clarify which cluster type this is being deployed into? Generic k8s, GKE, or OpenShift?

Which specific release of `voice-agent` are you attempting to use? The error you are showing wouldn't come from either release that exists on edge. voice-agent-100.0.1000001 or voice-agent-100.0.1000003

**Comment by xuheng44** [comment]
@DFHicks  I used Microk8s for PE installation. 

Below is from  describe pod:

[genesys@VM-4-14-centos agent]$ k describe pod voice-agent-689b966fcd-646h7 -n voice
Name:           voice-agent-689b966fcd-646h7
Namespace:      voice
Priority:       0
Node:           vm-4-14-centos/10.0.4.14
Start Time:     Tue, 31 May 2022 09:30:53 +0800
Labels:         app.kubernetes.io/instance=voice-agent
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=voice-agent
                app.kubernetes.io/version=1.0
                consul.hashicorp.com/connect-inject-managed-by=consul-k8s-endpoints-controller
                consul.hashicorp.com/connect-inject-status=injected
                helm.sh/chart=voice-agent-100.0.1000006
                pod-template-hash=689b966fcd
                service=voice
                servicename=voice-agent
Annotations:    checksum/config: a1c902e0d4687e9cb2e3b04bab4172a0f46ce657b1b738b06eea67faac3a8ed3
                consul.hashicorp.com/connect-inject: true
                consul.hashicorp.com/connect-inject-status: injected
                consul.hashicorp.com/connect-service: voice-agent
                consul.hashicorp.com/connect-service-port: 11000
                consul.hashicorp.com/connect-service-upstreams: voice-config:9100
                consul.hashicorp.com/original-pod:
                  {"kind":"Pod","apiVersion":"v1","metadata":{"generateName":"voice-agent-689b966fcd-","creationTimestamp":null,"labels":{"app.kubernetes.io...
                consul.hashicorp.com/service-tags: $POD_NAME
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/voice-agent-689b966fcd
Init Containers:
  copy-consul-bin:
    Container ID:  
    Image:         hashicorp/consul:1.12.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
      cp /bin/consul /consul/connect-inject/consul
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  150Mi
    Requests:
      cpu:        50m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /consul/connect-inject from consul-connect-inject-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tgt8m (ro)
  consul-connect-inject-init:
    Container ID:  
    Image:         hashicorp/consul-k8s-control-plane:0.44.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
      
      export CONSUL_HTTP_ADDR="https://${HOST_IP}:8501"
      export CONSUL_GRPC_ADDR="https://${HOST_IP}:8502"
      export CONSUL_CACERT=/consul/connect-inject/consul-ca.pem
      cat <<EOF >/consul/connect-inject/consul-ca.pem
      -----BEGIN CERTIFICATE-----
      MIIC6jCCApGgAwIBAgIQIqWz7HHtaElG/GjpBpthXjAKBggqhkjOPQQDAjCBuDEL
      MAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2Nv
      MRowGAYDVQQJExExMDEgU2Vjb25kIFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAV
      BgNVBAoTDkhhc2hpQ29ycCBJbmMuMT8wPQYDVQQDEzZDb25zdWwgQWdlbnQgQ0Eg
      NDYwNTQxMzAxMjI3Njk2MDcyNTk3Mjg4MDQ5MDkyNDQxNzg3ODIwHhcNMjIwNTI3
      MDI1MDMwWhcNMjcwNTI2MDI1MDMwWjCBuDELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
      AkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQJExExMDEgU2Vjb25k
      IFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAVBgNVBAoTDkhhc2hpQ29ycCBJbmMu
      MT8wPQYDVQQDEzZDb25zdWwgQWdlbnQgQ0EgNDYwNTQxMzAxMjI3Njk2MDcyNTk3
      Mjg4MDQ5MDkyNDQxNzg3ODIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ2R5wq
      TPyK4tcJYDAsrMkMCCkfugYwJiDlk9gbZembHaNpCsbjlj4gAdaLKnXcK3omFjYV
      bwSJ0+1LQsTE74jto3sweTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB
      /zApBgNVHQ4EIgQgwiUak8qMAZTejyMnrksbQ6u0W2hmBhtDPU6Ft2KUg8YwKwYD
      VR0jBCQwIoAgwiUak8qMAZTejyMnrksbQ6u0W2hmBhtDPU6Ft2KUg8YwCgYIKoZI
      zj0EAwIDRwAwRAIgZiTVNz6KGU5dCtIVDxSoJGykyA9QnlsTgdmTS94h8PoCIBYm
      bGchEGqUJngJRfEklPp7oUKO93EGzbczDKGLgvIw
      -----END CERTIFICATE-----
      
      EOF
      consul-k8s-control-plane connect-init -pod-name=${POD_NAME} -pod-namespace=${POD_NAMESPACE} \
        -consul-api-timeout=5s \
        -acl-auth-method="consul-k8s-auth-method" \
        -service-account-name="voice-agent" \
        -service-name="voice-agent" \
        -bearer-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token \
      
      # Generate the envoy bootstrap code
      /consul/connect-inject/consul connect envoy \
        -proxy-id="$(cat /consul/connect-inject/proxyid)" \
        -token-file="/consul/connect-inject/acl-token" \
        -bootstrap > /consul/connect-inject/envoy-bootstrap.yaml
      
      # Apply traffic redirection rules.
      /consul/connect-inject/consul connect redirect-traffic \
        -token-file="/consul/connect-inject/acl-token" \
        -proxy-id="$(cat /consul/connect-inject/proxyid)" \
        -proxy-uid=5995
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  150Mi
    Requests:
      cpu:     50m
      memory:  25Mi
    Environment:
      HOST_IP:         (v1:status.hostIP)
      POD_IP:          (v1:status.podIP)
      POD_NAME:       voice-agent-689b966fcd-646h7 (v1:metadata.name)
      POD_NAMESPACE:  voice (v1:metadata.namespace)
    Mounts:
      /consul/connect-inject from consul-connect-inject-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tgt8m (ro)
Containers:
  voice-agent:
    Container ID:   
    Image:          pureengage-docker-staging.jfrog.io/auth/voice/agent_node:1.0
    Image ID:       
    Port:           11000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  512Mi
    Requests:
      cpu:      250m
      memory:   256Mi
    Liveness:   http-get http://:20300/agent_node/health delay=20s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:20400/agent_node/health delay=20s timeout=5s period=10s #success=1 #failure=3
    Environment Variables from:
      voice-agent-configmap  ConfigMap  Optional: false
    Environment:
      HOST_IP:                             (v1:status.hostIP)
      HOST_NAME:                           (v1:spec.nodeName)
      POD_IP:                              (v1:status.podIP)
      POD_NAME:                           voice-agent-689b966fcd-646h7 (v1:metadata.name)
      REDIS_CACHE_KEY:                    /opt/genesys/redis-secret/redis-agent-state
      REDIS_TENANT_STREAM_KEY:            /opt/genesys/redis-tenant-secret/redis-tenant-stream
      SERVICE_CONSUL_ACL_TOKEN:           /opt/genesys/consul-shared-secret/consul-consul-voice-token
      kafka-secrets-westus2-dev:          /opt/genesys/kafka-shared-secret-westus2-dev/kafka-secrets
      kafka-secrets-eastus2-dev:          /opt/genesys/kafka-shared-secret-eastus2-dev/kafka-secrets
      VOICE_CONFIG_CONNECT_SERVICE_HOST:  127.0.0.1
      VOICE_CONFIG_CONNECT_SERVICE_PORT:  9100
    Mounts:
      /opt/genesys/consul-shared-secret from consul-shared-secret (ro)
      /opt/genesys/kafka-shared-secret-eastus2-dev from kafka-shared-secret-eastus2-dev (ro)
      /opt/genesys/kafka-shared-secret-westus2-dev from kafka-shared-secret-westus2-dev (ro)
      /opt/genesys/redis-secret from redis-cache-secret (ro)
      /opt/genesys/redis-tenant-secret from redis-tenant-secret (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tgt8m (ro)
  envoy-sidecar:
    Container ID:  
    Image:         envoyproxy/envoy:v1.22.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      envoy
      --config-path
      /consul/connect-inject/envoy-bootstrap.yaml
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      HOST_IP:   (v1:status.hostIP)
    Mounts:
      /consul/connect-inject from consul-connect-inject-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tgt8m (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  consul-shared-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  consul-voice-token
    Optional:    false
  redis-cache-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redis-agent-token
    Optional:    false
  redis-tenant-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redis-tenant-token
    Optional:    false
  kafka-shared-secret-westus2-dev:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kafka-secrets-token-westus2-dev
    Optional:    false
  kafka-shared-secret-eastus2-dev:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kafka-secrets-token-eastus2-dev
    Optional:    false
  kube-api-access-tgt8m:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
  consul-connect-inject-data:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  FailedMount  4m46s (x84 over 23h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[kafka-shared-secret-westus2-dev kafka-shared-secret-eastus2-dev], unattached volumes=[redis-tenant-secret kafka-shared-secret-westus2-dev kafka-shared-secret-eastus2-dev consul-connect-inject-data kube-api-access-tgt8m consul-shared-secret redis-cache-secret]: timed out waiting for the condition
[genesys@VM-4-14-centos agent]$ k describe pod voice-agent-689b966fcd-646h7 -n voice
Name:           voice-agent-689b966fcd-646h7
Namespace:      voice
Priority:       0
Node:           vm-4-14-centos/10.0.4.14
Start Time:     Tue, 31 May 2022 09:30:53 +0800
Labels:         app.kubernetes.io/instance=voice-agent
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=voice-agent
                app.kubernetes.io/version=1.0
                consul.hashicorp.com/connect-inject-managed-by=consul-k8s-endpoints-controller
                consul.hashicorp.com/connect-inject-status=injected
                helm.sh/chart=voice-agent-100.0.1000006
                pod-template-hash=689b966fcd
                service=voice
                servicename=voice-agent
Annotations:    checksum/config: a1c902e0d4687e9cb2e3b04bab4172a0f46ce657b1b738b06eea67faac3a8ed3
                consul.hashicorp.com/connect-inject: true
                consul.hashicorp.com/connect-inject-status: injected
                consul.hashicorp.com/connect-service: voice-agent
                consul.hashicorp.com/connect-service-port: 11000
                consul.hashicorp.com/connect-service-upstreams: voice-config:9100
                consul.hashicorp.com/original-pod:
                  {"kind":"Pod","apiVersion":"v1","metadata":{"generateName":"voice-agent-689b966fcd-","creationTimestamp":null,"labels":{"app.kubernetes.io...
                consul.hashicorp.com/service-tags: $POD_NAME
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/voice-agent-689b966fcd
Init Containers:
  copy-consul-bin:
    Container ID:  
    Image:         hashicorp/consul:1.12.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
      cp /bin/consul /consul/connect-inject/consul
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  150Mi
    Requests:
      cpu:        50m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /consul/connect-inject from consul-connect-inject-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tgt8m (ro)
  consul-connect-inject-init:
    Container ID:  
    Image:         hashicorp/consul-k8s-control-plane:0.44.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -ec
      
      export CONSUL_HTTP_ADDR="https://${HOST_IP}:8501"
      export CONSUL_GRPC_ADDR="https://${HOST_IP}:8502"
      export CONSUL_CACERT=/consul/connect-inject/consul-ca.pem
      cat <<EOF >/consul/connect-inject/consul-ca.pem
      -----BEGIN CERTIFICATE-----
      MIIC6jCCApGgAwIBAgIQIqWz7HHtaElG/GjpBpthXjAKBggqhkjOPQQDAjCBuDEL
      MAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2Nv
      MRowGAYDVQQJExExMDEgU2Vjb25kIFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAV
      BgNVBAoTDkhhc2hpQ29ycCBJbmMuMT8wPQYDVQQDEzZDb25zdWwgQWdlbnQgQ0Eg
      NDYwNTQxMzAxMjI3Njk2MDcyNTk3Mjg4MDQ5MDkyNDQxNzg3ODIwHhcNMjIwNTI3
      MDI1MDMwWhcNMjcwNTI2MDI1MDMwWjCBuDELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
      AkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQJExExMDEgU2Vjb25k
      IFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAVBgNVBAoTDkhhc2hpQ29ycCBJbmMu
      MT8wPQYDVQQDEzZDb25zdWwgQWdlbnQgQ0EgNDYwNTQxMzAxMjI3Njk2MDcyNTk3
      Mjg4MDQ5MDkyNDQxNzg3ODIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ2R5wq
      TPyK4tcJYDAsrMkMCCkfugYwJiDlk9gbZembHaNpCsbjlj4gAdaLKnXcK3omFjYV
      bwSJ0+1LQsTE74jto3sweTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB
      /zApBgNVHQ4EIgQgwiUak8qMAZTejyMnrksbQ6u0W2hmBhtDPU6Ft2KUg8YwKwYD
      VR0jBCQwIoAgwiUak8qMAZTejyMnrksbQ6u0W2hmBhtDPU6Ft2KUg8YwCgYIKoZI
      zj0EAwIDRwAwRAIgZiTVNz6KGU5dCtIVDxSoJGykyA9QnlsTgdmTS94h8PoCIBYm
      bGchEGqUJngJRfEklPp7oUKO93EGzbczDKGLgvIw
      -----END CERTIFICATE-----
      
      EOF
      consul-k8s-control-plane connect-init -pod-name=${POD_NAME} -pod-namespace=${POD_NAMESPACE} \
        -consul-api-timeout=5s \
        -acl-auth-method="consul-k8s-auth-method" \
        -service-account-name="voice-agent" \
        -service-name="voice-agent" \
        -bearer-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token \
      
      # Generate the envoy bootstrap code
      /consul/connect-inject/consul connect envoy \
        -proxy-id="$(cat /consul/connect-inject/proxyid)" \
        -token-file="/consul/connect-inject/acl-token" \
        -bootstrap > /consul/connect-inject/envoy-bootstrap.yaml
      
      # Apply traffic redirection rules.
      /consul/connect-inject/consul connect redirect-traffic \
        -token-file="/consul/connect-inject/acl-token" \
        -proxy-id="$(cat /consul/connect-inject/proxyid)" \
        -proxy-uid=5995
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  150Mi
    Requests:
      cpu:     50m
      memory:  25Mi
    Environment:
      HOST_IP:         (v1:status.hostIP)
      POD_IP:          (v1:status.podIP)
      POD_NAME:       voice-agent-689b966fcd-646h7 (v1:metadata.name)
      POD_NAMESPACE:  voice (v1:metadata.namespace)
    Mounts:
      /consul/connect-inject from consul-connect-inject-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tgt8m (ro)
Containers:
  voice-agent:
    Container ID:   
    Image:          pureengage-docker-staging.jfrog.io/auth/voice/agent_node:1.0
    Image ID:       
    Port:           11000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  512Mi
    Requests:
      cpu:      250m
      memory:   256Mi
    Liveness:   http-get http://:20300/agent_node/health delay=20s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:20400/agent_node/health delay=20s timeout=5s period=10s #success=1 #failure=3
    Environment Variables from:
      voice-agent-configmap  ConfigMap  Optional: false
    Environment:
      HOST_IP:                             (v1:status.hostIP)
      HOST_NAME:                           (v1:spec.nodeName)
      POD_IP:                              (v1:status.podIP)
      POD_NAME:                           voice-agent-689b966fcd-646h7 (v1:metadata.name)
      REDIS_CACHE_KEY:                    /opt/genesys/redis-secret/redis-agent-state
      REDIS_TENANT_STREAM_KEY:            /opt/genesys/redis-tenant-secret/redis-tenant-stream
      SERVICE_CONSUL_ACL_TOKEN:           /opt/genesys/consul-shared-secret/consul-consul-voice-token
      kafka-secrets-westus2-dev:          /opt/genesys/kafka-shared-secret-westus2-dev/kafka-secrets
      kafka-secrets-eastus2-dev:          /opt/genesys/kafka-shared-secret-eastus2-dev/kafka-secrets
      VOICE_CONFIG_CONNECT_SERVICE_HOST:  127.0.0.1
      VOICE_CONFIG_CONNECT_SERVICE_PORT:  9100
    Mounts:
      /opt/genesys/consul-shared-secret from consul-shared-secret (ro)
      /opt/genesys/kafka-shared-secret-eastus2-dev from kafka-shared-secret-eastus2-dev (ro)
      /opt/genesys/kafka-shared-secret-westus2-dev from kafka-shared-secret-westus2-dev (ro)
      /opt/genesys/redis-secret from redis-cache-secret (ro)
      /opt/genesys/redis-tenant-secret from redis-tenant-secret (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tgt8m (ro)
  envoy-sidecar:
    Container ID:  
    Image:         envoyproxy/envoy:v1.22.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      envoy
      --config-path
      /consul/connect-inject/envoy-bootstrap.yaml
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      HOST_IP:   (v1:status.hostIP)
    Mounts:
      /consul/connect-inject from consul-connect-inject-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tgt8m (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  consul-shared-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  consul-voice-token
    Optional:    false
  redis-cache-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redis-agent-token
    Optional:    false
  redis-tenant-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redis-tenant-token
    Optional:    false
  kafka-shared-secret-westus2-dev:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kafka-secrets-token-westus2-dev
    Optional:    false
  kafka-shared-secret-eastus2-dev:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kafka-secrets-token-eastus2-dev
    Optional:    false
  kube-api-access-tgt8m:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
  consul-connect-inject-data:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  2m14s (x699 over 23h)  kubelet  MountVolume.SetUp failed for volume "kafka-shared-secret-eastus2-dev" : secret "kafka-secrets-token-eastus2-dev" not found

**Comment by DFHicks** [comment]
@xuheng44 Please take a look at the v0.3.0 release. We have changed our workflow to incorporate a common variable for your personal image repository.
`IMAGE_REGISTRY` is now used within each example override, and stored in your GitHub secrets.

Example:
```
image:
  registry: $IMAGE_REGISTRY
  pullPolicy: Always
  imagePullSecrets: "pullsecret"
```

To ensure your cluster has the needed access details to your image repository, please be sure to add it to your cluster:
Example:
```
  kubectl create secret docker-registry pullsecret \
       --docker-server=repository.path \
      --docker-username=user --docker-password=token
```

https://github.com/genesys/multicloud-services/blob/main/examples-generic-kubernetes/github-actions/README.md#-considerations

**Comment by xuheng44** [comment]
@DFHicks 
I already added below two as guide:

1. Helm repo: 
helm repo add helm-staging https://pureengage.jfrog.io/artifactory/api/helm/helm-staging --username skyxu --password XXXXXXXXXXXXXXXXX
3. docker-registry 
ubectl create secret docker-registry genesys-jfrog --docker-server=pureengage-docker-staging.jfrog.io --docker-username=skyxu --docker-password=XXXXXXXXXXXXXXX  -n voice

I had sucessfully install gauth by below Image repository setting in overrides_values.yaml:
registry: pureengage-docker-staging.jfrog.io/auth

But i don't know the corrent address  for image registory in voice-agent override_values.yaml.
i had tried pureengage-docker-staging.jfrog.io and pureengage-docker-staging.jfrog.io/voice, both failed.

the error info is :
belet Failed to pull image "pureengage-docker-staging.jfrog.io/voice/agent_node:1.0": rpc error: code = NotFound desc = failed to pull and unpack image "pureengage-docker-staging.jfrog.io/voice/agent_node:1.0":

Can you help to provide correct address? i used the standard jfrog registory.

Thanks
Sky
