### ISSUE TITLE
voice-voicemail install issue

### ISSUE THREAD

**Issue by dforrest100** [genesys/multicloud-services#28]
Hi @DFHicks ,

I got through gauth and am working on voice.  Ran into this error that I cant sort out:

Release "voice-voicemail" does not exist. Installing it now.
Error: failed to download "helm_repo/voice-voicemail" at version "100.0.1000008"
Error: Process completed with exit code 1.

Thanks!
Dan

Full logs below:

[rawlogs.txt](https://github.com/genesys/multicloud-services/files/8863075/rawlogs.txt)

**Comment by AndyVoutour** [comment]
Hi @dforrest100 ,

@DFHicks and I tracked this down. Looks like the versions for the voice/voicemail release specifically aren't correct.

Can you change two files manually?

- github-actions/voice/11_chart_voice-voicemail/01_release_voice-voicemail/override_values.yaml - change the entry to be:

```yaml
  version: 100.0.1000009
```

-  github-actions/voice/11_chart_voice-voicemail/chart.ver - change the entry to be:
```
100.0.1000011
```
Then re-run and let us know?

We'll be updating the version of the voice services this month to address this voice-voicemail issue specifically and we'll also working on putting some more processes/tracking in place to hopefully ensure this doesn't happen again in the future with other services. We're aware of it now, so we'll be keeping an eye on it.

**Comment by dforrest100** [comment]
did the trick.  thanks!

**Comment by AndyVoutour** [comment]
Recommended version changes, putting process in place for tracking this going forward.

**Comment by DFHicks** [comment]
> Recommended version changes, putting process in place for tracking this going forward.

Voice services versions have been updated to latest published release. https://github.com/genesys/multicloud-services/pull/29
