### ISSUE TITLE
Failed to Deploy infra (install postgres pgdb-rptrlt)

### ISSUE THREAD

**Issue by rowiebiz82** [genesys/multicloud-services#87]
### What happened?

The postgres instance pgdb-rptrlt failed to deploy. 

### Cluster

GKE

### What service are you having issues with?

infra

### Relevant log output

```shell
shell: /usr/bin/bash -e {0}
  env:
    HELM_REGISTRY: ***
    HELM_REGISTRY_USER: ***
    HELM_REGISTRY_TOKEN: ***
    IMAGE_REGISTRY: ***
    GKE_SA_KEY_NAME: GKE_SA_KEY
    GKE_PROJECT_NAME: GKE_PROJECT
    GKE_CLUSTER: ***-gke2
    GKE_ZONE: us-central1-c
    DOMAIN: ***gen2.tk
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    KUBECONFIG: /home/runner/work/rowie-multicloudcx1/rowie-multicloudcx1/9bdec865-2db8-485f-b88a-0970c9622323
    NS: infra
Installing...
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by DFHicks** [comment]
@rowiebiz82 

Please make sure the prerequisites are in place for monitoring as we flag for prometheus in the helm override. (see [monitoring](https://github.com/genesys/multicloud-services/tree/main/examples-gke/github-actions/monitoring))

Try a singular instance install afterwards:

`install postgres pgdb-rptrt`

**Comment by rowiebiz82** [comment]
Yeah it was typo error on my end. It is indeed just pgdb-rptrt. You can close this.
