### ISSUE TITLE
[BUG]: gws installation failure due to ***gws/index.yaml : 404 Not Found

### ISSUE THREAD

**Issue by samukwak** [genesys/multicloud-services#91]
### What happened?

gws installation fails due to ***gws/index.yaml : 404 Not Found. 

I've tried the following settings in \gws\01_chart_gws-services\override_values.yaml ang got the same error:
- registry: $IMAGE_REGISTRY/gws
- registry: pureengage-docker-staging.jfrog.io/gws
- registry: "pureengage-docker-staging.jfrog.io/gws"

### Cluster

GKE

### What service are you having issues with?

gws

### Relevant log output

```shell
Run helm repo add --force-update helm_repo ***gws \
  
Error: looks like "***gws" is not a valid chart repository or cannot be reached: failed to fetch ***gws/index.yaml : 404 Not Found
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by samukwak** [comment]
Is index.yaml supposed to be available at https://pureengage.jfrog.io/ui/native/docker-staging/gws/?
`Index of docker-staging/gws
Name	Last Modified	Size	Download Link
[../](https://pureengage.jfrog.io/artifactory/docker-staging/)			
[auth-system-installer/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/auth-system-installer/)	15-04-20 12:42:35 +1000		
[base/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/base/)	10-01-19 19:24:08 +1000		
[centos/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/centos/)	27-06-21 08:09:04 +1000		
[elasticsearch/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/elasticsearch/)	27-06-21 08:11:15 +1000		
[gss-status-config/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gss-status-config/)	16-07-20 07:26:17 +1000		
[gws-api-analytics/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-api-analytics/)	31-10-18 02:30:36 +1000		
[gws-api-configuration/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-api-configuration/)	11-01-22 00:04:07 +1000		
[gws-app-applicationmanagement/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-applicationmanagement/)	14-11-18 17:04:27 +1000		
[gws-app-console/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-console/)	26-04-19 04:10:35 +1000		
[gws-app-developerconsole/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-developerconsole/)	16-03-18 04:27:05 +1000		
[gws-app-logviewer/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-logviewer/)	10-01-19 10:44:09 +1000		
[gws-app-provisioning/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-provisioning/)	16-03-18 07:57:49 +1000		
[gws-app-sandboxmanagement/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-sandboxmanagement/)	21-02-19 23:58:01 +1000		
[gws-app-workspace/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-workspace/)	10-03-18 14:45:46 +1000		
[gws-app-workspace4/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-workspace4/)	01-02-22 02:09:02 +1000		
[gws-app-workspacev4/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-app-workspacev4/)	01-02-22 17:35:01 +1000		
[gws-base-nginx/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-base-nginx/)	05-09-20 04:57:50 +1000		
[gws-confserv-postgres/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-confserv-postgres/)	06-04-22 00:01:25 +1000		
[gws-core-auth/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-core-auth/)	10-03-18 14:33:10 +1000		
[gws-core-auth-ui/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-core-auth-ui/)	13-06-18 01:22:37 +1000		
[gws-core-environment/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-core-environment/)	10-03-18 11:33:23 +1000		
[gws-core-keystore/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-core-keystore/)	05-10-19 13:00:18 +1000		
[gws-data-config/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-data-config/)	14-03-18 05:30:09 +1000		
[gws-event-consumer/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-event-consumer/)	03-09-21 23:37:14 +1000		
[gws-event-consumer-api-sample/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-event-consumer-api-sample/)	17-12-21 02:09:11 +1000		
[gws-event-consumer-login/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-event-consumer-login/)	29-11-21 22:28:22 +1000		
[gws-platform-ares/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-ares/)	13-03-18 06:49:38 +1000		
[gws-platform-cache/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-cache/)	12-05-22 13:42:55 +1000		
[gws-platform-chat/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-chat/)	10-03-18 14:26:43 +1000		
[gws-platform-configexporter/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-configexporter/)	16-01-20 08:11:13 +1000		
[gws-platform-configuration/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-configuration/)	10-03-18 14:39:23 +1000		
[gws-platform-datacollector/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-datacollector/)	24-03-18 09:08:13 +1000		
[gws-platform-feedback/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-feedback/)	23-02-19 06:21:12 +1000		
[gws-platform-ixn/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-ixn/)	12-03-18 19:04:39 +1000		
[gws-platform-ocs/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-ocs/)	16-03-18 05:13:28 +1000		
[gws-platform-setting/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-setting/)	10-05-18 08:36:26 +1000		
[gws-platform-statistics/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-statistics/)	16-03-18 06:09:07 +1000		
[gws-platform-ucs/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-ucs/)	12-03-18 20:38:21 +1000		
[gws-platform-voice/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-platform-voice/)	15-03-18 16:55:00 +1000		
[gws-postgres/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-postgres/)	06-04-22 00:08:54 +1000		
[gws-service-voice/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-service-voice/)	04-08-22 08:39:10 +1000		
[gws-system-installer/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-system-installer/)	05-08-19 20:10:47 +1000		
[gws-system-loadbalancer/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-system-loadbalancer/)	14-03-18 07:21:50 +1000		
[gws-system-migrate/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-system-migrate/)	12-07-19 20:02:17 +1000		
[gws-system-nginx/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-system-nginx/)	21-11-18 06:06:04 +1000		
[gws-system-proxy/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-system-proxy/)	12-05-18 08:02:44 +1000		
[gws-system-replication/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-system-replication/)	12-07-19 07:59:52 +1000		
[gws-ui-applicationmanagement/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-ui-applicationmanagement/)	06-03-19 09:12:05 +1000		
[gws-ui-auth/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-ui-auth/)	26-07-18 07:02:42 +1000		
[gws-ui-crmworkspace/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-ui-crmworkspace/)	11-10-18 05:02:11 +1000		
[gws-ui-developerconsole/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-ui-developerconsole/)	16-03-18 07:40:33 +1000		
[gws-ui-logviewer/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-ui-logviewer/)	28-02-19 23:29:44 +1000		
[gws-ui-provisioning/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-ui-provisioning/)	16-03-18 10:12:03 +1000		
[gws-ui-sandboxmanagement/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-ui-sandboxmanagement/)	28-02-19 23:04:30 +1000		
[gws-ui-workspace/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/gws-ui-workspace/)	14-03-18 15:34:58 +1000		
[pre-staging/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/pre-staging/)	28-09-19 10:22:24 +1000		
[redis/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/redis/)	27-06-21 08:05:35 +1000		
[third-party/](https://pureengage.jfrog.io/artifactory/docker-staging/gws/third-party/)	27-06-19 13:50:28 +1000`

**Comment by DFHicks** [comment]
`$IMAGE_REGISTRY` is a variable pulled from your github secrets loaded as per the [deploy_service.yaml](https://github.com/genesys/multicloud-services/blob/main/examples-gke/github-actions/.github/workflows/deploy_service.yaml) workflow.

As you are using the Genesys internal repository, we'd expect this to be set to: `pureengage-docker-staging.jfrog.io`

**Comment by samukwak** [comment]
pureengage-docker-staging.jfrog.io is what I set in override_values.yaml instead of using a variable ($IMAGE_REGISTRY) from deployment-secrets. This works fine with gauth, voice microservices, and tenant deployment.

The issue is that the custom script appears to attempt to fetch gws/index.yaml, which doesn't exist, and this results in 404. This does not happen with gauth, voice microservices, and tenant deployment.

**Comment by DFHicks** [comment]
The workflow is looking for the following:

```
env:
  # 🖊️ EDIT to change the helm registry settings.
  # Registries such as Jfrog, GHCR, Quay.io, and Docker Hub are supported.
  HELM_REGISTRY:            ${{ secrets.HELM_REGISTRY }}
  HELM_REGISTRY_USER:       ${{ secrets.HELM_REGISTRY_USER }}          
  HELM_REGISTRY_TOKEN:      ${{ secrets.HELM_REGISTRY_TOKEN }}
  IMAGE_REGISTRY:           ${{ secrets.IMAGE_REGISTRY }}
```

Which, as part of the initialization, loads your registry:

```
    - name: Helm repo add
      run: |
        helm repo add --force-update helm_repo ${{ env.HELM_REGISTRY }}${{ github.event.inputs.helmrepo }} \
          --username ${{ env.HELM_REGISTRY_USER }} --password ${{ env.HELM_REGISTRY_TOKEN }}
```
 
Can you confirm this secret was set within github? `HELM_REGISTRY`

**Comment by samukwak** [comment]
I was away. Yes, HELM_REGISTRY is one of secrets configured at ../settings/secrets/actions:
```
GKE_PROJECT
Updated on Jun 16
GKE_SA_KEY
[Update](https://github.com/samukwak/gcp-gke-pe/settings/secrets/actions/GKE_PROJECT)d on Jun 16
HELM_REGISTRY
Updated on Jun 16
HELM_REGISTRY_TOKEN
[Update](https://github.com/samukwak/gcp-gke-pe/settings/secrets/actions/GKE_SA_KEY)d on Jun 16
HELM_REGISTRY_USER
Updated on Jun 16
```

**Comment by johnebaird** [comment]
@samukwak  when deploying what did you specify 'helm repo name' that should be helm-stage you could have typed gws in there (like you would for service / namespace) 

the 'helm repo add' step is in the same deploy_service.yaml used for every service so there's nothing gws specific yet

**Comment by samukwak** [comment]
Based on the log output, I must have mistakenly used gws instead of helm-stage... My apologies.

The error doesn't happen with `Run helm repo add --force-update helm_repo ***helm-stage \`.

I close this task.

**Comment by johnebaird** [comment]
@samukwak no worries glad its working
